version: '3.7'

services: 
  
  backend:
    image: backend-nodejs
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/docker-volume/ssl2:/root
    container_name: "backend"
